const cartesJSON =[
    // ==========================================
    // ANCIENNES CARTES (avec 1 seul commentaire)
    // ==========================================
    { category: "TRASH", text: "Qui a le QI le plus proche de la température ambiante (en Celsius) ?", comments: ["Il est con ce pd..."] },
    { category: "TRASH", text: "Qui est le plus hypocrite du groupe ?", comments:["C'est le côté bonne femme de $pseudo qui parle."] },
    { category: "TRASH", text: "Qui a la pire hygiène de vie ?", comments:["T'attends la saison des pluies pour te doucher $pseudo ?"] },
    { category: "TRASH", text: "Qui a l'humour le plus beauf ?", comments: ["Pouet pouet petit blagueur !"] },
    { category: "TRASH", text: "Qui pleure à la moindre critique constructive ?", comments: ["Sors les mouchoirs $pseudo, le monde est méchant."] },
    { category: "SOIREE", text: "Qui est systématiquement le premier à vomir en soirée ?", comments:["Quoi ? L'alcool c'est pas cool ?!"] },
    { category: "SOIREE", text: "Qui monopolise toujours la musique pour mettre de la merde ?", comments:["Le compte spotify le moins bien rentabilisé."] },
    { category: "SOIREE", text: "Qui devient le plus agressif avec 2 grammes dans le sang ?", comments:["Quand $pseudo est bourré il se prend pour McGregor."] },
    { category: "LOVE", text: "Qui est le plus gros canard en couple ?", comments:["Tu demandes la permission pour respirer aussi, $pseudo ?"] },
    { category: "LOVE", text: "Qui a les pires goûts en matière d'ex ?", comments:["$pseudo mise sur la quantité plutôt que la qualité..."] },
    { category: "SEXE", text: "Qui fait le plus de bruit au lit ?", comments: ["C'est pas une compète $pseudo, t'es pas dans un film de cul."] },
    { category: "LOVE", text: "Qui pourrait espionner le téléphone de sa moitié pendant son sommeil ?", comments: ["Big Brother c'est toi ?"] },
    { category: "LOVE", text: "Qui est capable de se remettre avec son ex ?", comments:["En SAH $pseudo faut passer à autre chose."] },
    { category: "SEXE", text: "Qui a les fantasmes les plus bizarres ?", comments:["Le BDSM c'est mignon à côté de ce que regarde $pseudo."] },
    { category: "LOVE", text: "Qui pleure après l'amour ?", comments: ["Au moins c'est pas PENDANT. C'est déjà ça."] },
    { category: "ARGENT", text: "Qui est capable de réclamer un virement Lydia de 50 centimes ?", comments:["SALE JUIF."] },
    { category: "ARGENT", text: "Qui pourrait vendre les cadeaux de Noël qu'on lui offre sur Vinted ?", comments: ["Le capitalisme est fier de toi $pseudo."] },
    { category: "SURVIE", text: "Qui mourrait en premier dans une invasion de zombies ?", comments:["Désolé $pseudo, mais même en zombie tu serais pas une menace"] },
    { category: "WTF", text: "Qui croit aux théories du complot les plus absurdes ?", comments: ["C'est ça, et les pigeons sont des drones du gouvernement $pseudo ?"] },
    { category: "WTF", text: "Qui a l'historique internet le plus inavouable ?", comments: ["Le FBI a un dossier complet sur toi, $pseudo."] },
    { category: "WTF", text: "Qui pourrait devenir un serial killer ?", comments: ["Me regarde pas comme ça $pseudo. Tu me fais peur..."] },
    { category: "WTF", text: "Qui se ferait arnaquer par le Prince du Nigéria par mail ?", comments:["Donne-moi ton code de carte bleue $pseudo, je te le garde en sécurité."] },
    { category: "WTF", text: "Qui pourrait parler à un mur si on ne l'arrête pas ?", comments: ["$pseudo a obtenu son diplôme : 'Mashallah tu parles trop'"] },
    { category: "QUOTIDIEN", text: "Qui est chroniquement en retard, même quand on lui donne une fausse heure ?", comments: ["Vous êtes de la famille Delaboca non ?"] },
    { category: "QUOTIDIEN", text: "Qui annule toujours ses plans à la dernière minute ?", comments:["On sait que tu es juste devant Netflix en pyjama, $pseudo."] },
    { category: "QUOTIDIEN", text: "Qui passe 8 heures par jour sur TikTok ?", comments:["Brainroted."] },
    { category: "QUOTIDIEN", text: "Qui laisse traîner sa vaisselle pendant une semaine entière ?", comments:["Si tu laisses traîner assez longtemps elle va peut-être se faire toute seule."] },
    { category: "QUOTIDIEN", text: "Qui pourrait oublier de nourrir son enfant ?", comments:["Qui voudrait un enfant avec $pseudo même ?"] },
    { category: "QUOTIDIEN", text: "Qui ne répond jamais aux messages ?", comments: ["$pseudo a pas ton temps. Il est busy ok ?"] },
    { category: "QUOTIDIEN", text: "Qui s'énerve tout seul devant les jeux vidéo ?", comments:["T'es pas un Sayan, crier te rend pas plus fort $pseudo."] },
    { category: "QUOTIDIEN", text: "Qui ment sur la taille de ce qu'il mange quand il est 'au régime' ?", comments:["$pseudo ? Fit and fun ? J'en doute"] },
    { category: "EGO", text: "Qui s'aime beaucoup trop en regardant son reflet dans les vitrines ?", comments:["J'y crois pas comment j'suis beau !"] },
    { category: "EGO", text: "Qui ramène systématiquement la conversation à soi ?", comments:["$pseudo a le syndrome du personnage principal."] },
    { category: "EGO", text: "Qui est le plus susceptible de mentir pour impressionner des inconnus ?", comments:["Si $pseudo dit qu'il a pris un jet privé, il était dans le RER B."] },
    { category: "EGO", text: "Qui n'avoue jamais qu'il a tort, même face aux preuves ?", comments:["La mauvaise foi a un nom, et c'est $pseudo."] },
    { category: "STYLE", text: "Qui s'habille mal ?", comments: ["Je m'habille mal ?"] },
    { category: "STYLE", text: "Qui achète des vêtements hors de prix pour avoir l'air riche mais c'est raté ?", comments: ["Un mec moche en Gucci reste un mec moche. Tu le sais pourtant $pseudo..."] },
    { category: "STYLE", text: "Qui a eu la pire coupe de cheveux par le passé ?", comments:["$pseudo. Avoue. Même toi tu trouvais ça horrible."] },
    { category: "BOULOT", text: "Qui est le roi pour faire semblant de travailler ?", comments:["Je l'ai vu taffé une fois en 2008. Je crois."] },
    { category: "BOULOT", text: "Qui va se faire virer en premier pour incompétence ?", comments:["Chômage ! Je suis au chômage !"] },
    { category: "BOULOT", text: "Qui prend 4 pauses clopes d'une heure par jour ?", comments:["Commence jamais cette merde."] },
    { category: "BOULOT", text: "Qui dépense tout son salaire dès le 3 du mois ?", comments: ["Le banquier de $pseudo fait des cauchemars."] },

    // ==========================================
    // NOUVELLES CARTES (+ de 100 inédites)
    // ==========================================
    { category: "TRASH", text: "Qui est le plus gros forceur de la bande ?", comments:["Lâche le steak $pseudo. Vraiment."] },
    { category: "TRASH", text: "Qui ment le plus ?", comments:["Ça va finir par se voir $pseudo."] },
    { category: "TRASH", text: "Qui ferait la pire baby-sitter ?", comments: ["Préparez l'avis de recherches ça ira plus vite."] },
    { category: "TRASH", text: "Qui est le plus lâche face au danger ?", comments:["Au moins il arrivera rien de grave à $pseudo."] },
    { category: "SOIREE", text: "Qui s'endort toujours sur le canapé à 23h ?", comments: ["12h de sommeil minimum pour $pseudo."] },
    { category: "SOIREE", text: "Qui a les pires anecdotes de soirée alcoolisée ?", comments: ["Pose toi les bonnes questions $pseudo"] },
    { category: "SOIREE", text: "Qui envoie les pires messages bourrés à son ex ?", comments:["Confisquez-lui son téléphone, la dignité de $pseudo est en danger !"] },
    { category: "SOIREE", text: "Qui essaie de pécho tout ce qui bouge ?", comments:["$pseudo, cette chaudière."] },
    { category: "LOVE", text: "Qui est le roi/la reine des relations toxiques ?", comments: ["Oui $pseudo, c'est TOI le problème."] },
    { category: "LOVE", text: "Qui tombe amoureux(se) en 24h chrono ?", comments:["$pseudo, cette chaudière..."] },
    { category: "LOVE", text: "Qui se fait toujours friendzoner en beauté ?", comments: ["'Non mais $pseudo c'est comme un membre de ma famille quoi'"] },
    { category: "LOVE", text: "Qui fouille dans les DMs de son partenaire H24 ?", comments:["Tu as un sérieux problème de confiance en toi, $pseudo."] },
    { category: "LOVE", text: "Qui pardonne l'impardonnable par peur d'être seul(e) ?", comments:["Un peu d'amour propre, $pseudo, merde !"] },
    { category: "LOVE", text: "Qui crée des faux comptes pour stalker ses exs ?", comments: ["Le FBI recrute, $pseudo, tente ta chance."] },
    { category: "LOVE", text: "Qui est attiré par des personnes bien trop jeunes ?", comments: ["'Non mais dans lore elle a 1000 ans' C'est ça $pseudo? "] },
    { category: "SEXE", text: "Qui a le record de la relation la plus courte chronométrée ?", comments:["Une relation ça dure pas le temps d'un snap $pseudo."] },
    { category: "ARGENT", text: "Qui 'oublie' toujours son portefeuille au moment de payer l'addition ?", comments:["L'amnésie sélective de $pseudo frappe encore."] },
    { category: "WTF", text: "Qui pourrait manger de la pâtée pour chat par erreur et trouver ça bon ?", comments:["Tes papilles gustatives sont mortes, $pseudo."] },
    { category: "QUOTIDIEN", text: "Qui conduit comme un psychopathe ?", comments:["On a tous peur pour notre vie avec toi, $pseudo."] },
    { category: "QUOTIDIEN", text: "Qui est incapable de cuisiner autre chose que des pâtes au beurre ?", comments:["Gordon Ramsay ferait une crise cardiaque avec toi, $pseudo."] },
    { category: "EGO", text: "Qui est le plus mauvais perdant ?", comments: ["On va finir par cacher le Monopoly à cause de toi, $pseudo."] },
    { category: "EGO", text: "Qui fait des vocaux de 4 minutes pour ne rien dire ?", comments:["On fait tous 'x2' quand tu parles, $pseudo."] },
    { category: "EGO", text: "Qui donne des conseils de vie alors que la sienne est un chaos total ?", comments:["Gère tes propres problèmes d'abord, $pseudo."] },
    { category: "WTF", text: "Qui a le plus gros dossier photo compromettant dans les téléphones des autres ?", comments:["Le jour où on te fait chanter, t'es ruiné $pseudo."] },

    // ==========================================
    // AJOUTS SESSION 1
    // ==========================================
    { category: "SEXE", text: "Qui a la plus grosse ?", comments: ["T'as un python dans l'slibard $pseudo."] },
    { category: "STYLE", text: "Qui a les pires goûts musicaux ?", comments: ["$pseudo pisse littéralement dans des violons..."] },
    { category: "BOULOT", text: "Qui pourrait complètement se la couler douce au chômage ?", comments: ["Fais des gosses $pseudo, ça rapporte gros !"] },
    { category: "LOVE", text: "Qui pourrait pécho le crush de son pote ?", comments: ["Y'a pas d'soucis $pseudo, y'a pas d'soucis..."] },
    { category: "EGO", text: "Qui veut absolument toujours avoir le dernier mot ?", comments: ["Bravo, en votant pour $pseudo vous lui avez encore donné raison..."] },
    { category: "LOVE", text: "Qui semble être le moins hétéro ?", comments: ["Moi ça m'dérange pas $pseudo UwU"] },
    { category: "SURVIE", text: "Qui pourrait manger n'importe quoi du moment que ça se digère ?", comments: ["$pseudo mange même des planètes et des émotions", "J'suis dans la cuisine, tu boufferas évidemment c'que j'te prépare"] },
    { category: "QUOTIDIEN", text: "Qui a la pire vie ?", comments: ["Je t'aurais bien fait un câlin mais je fais pas dans la charité"] },
    { category: "SEXE", text: "Qui baise le moins ?", comments: ["Alors $pseudo, t'es plutôt mouchoir ou chaussette ?", "Y'a aucun problème avec ça gros looser que t'es $pseudo"] },
    { category: "SURVIE", text: "Qui est le moins sportif ?", comments: ["Non $pseudo, bouger ton gros cul jusqu'au frigo c'est pas du sport…"] },
    { category: "STYLE", text: "Qui a le visage le moins beau ?", comments: ["$pseudo… un visage que seule une mère peut aimer", "Oh la vache $pseudo t'as mangé un camion avant de venir ?"] },
    { category: "EGO", text: "Qui est le plus stupide ?", comments: ["Toi c'est sûr que tu connais le goût des couleurs", "Je crois que $pseudo sait compter jusqu'à Bleu", "Au village des idiots t'es l'idiot du village toi nan ?"] },
    { category: "EGO", text: "Qui sent le plus mauvais ?", comments: ["Merde $pseudo une douche c'est pas du luxe, j'ai failli vomir… 2 fois"] },

    // ==========================================
    // AJOUTS SESSION 2
    // ==========================================
    { category: "TRASH", text: "Qui a l'air le plus con sur ses photos ?", comments: ["Même Google a refusé de catégoriser $pseudo dans 'humains'"] },
    { category: "TRASH", text: "Qui ferait le pire président ?", comments: ["Kim Jong-Un fait moins peur que $pseudo avec du pouvoir"] },
    { category: "LOVE", text: "Qui a le plus de chances de finir seul avec un chat ?", comments: ["Au moins le chat il peut pas te ghoster $pseudo"] },
    { category: "LOVE", text: "Qui tomberait amoureux d'une IA ?", comments: ["$pseudo a déjà dit 'merci' à Siri... Il a dit MERCI !.."] },
    { category: "SEXE", text: "Qui a le plus de chances d'avoir un OnlyFans secret ?", comments: ["Allez pas voir ça en vaut pas la peine", "Abonnement à 4,99€/mois. $pseudo vaut même pas le prix..."] },
    { category: "SEXE", text: "Qui a forcément menti sur son body-count ?", comments: ["$pseudo a la même capote dans son portefeuille depuis 10 ans"] },
    { category: "SEXE", text: "Qui serait le pire coup de sa génération ?", comments: ["Avis Google : Déçu de $pseudo, je recommande pas", "$pseudo baise comme il cuisine, et il sait pas faire cuire des pâtes..."] },
    { category: "ARGENT", text: "Qui mourrait sans Fast Food ?", comments: ["Le sang de $pseudo c'est 80% de sauce Big Mac"] },
    { category: "ARGENT", text: "Qui emprunte de l'argent sans jamais rembourser ?", comments: ["Depuis son séjour à Tel-Aviv, $pseudo est un nouvel homme"] },
    { category: "WTF", text: "Qui pourrait rejoindre une secte sans s'en rendre compte ?", comments: ["Je vous assure que c'est pour les Resto du Cœur que je sacrifie des chèvres !"] },
    { category: "QUOTIDIEN", text: "Qui répond 'ça va' alors que clairement ça va pas ?", comments: ["Franchement j'aurais pu y croire si y'avait aucune corde autour de ton cou"] },
    { category: "EGO", text: "Qui prend le plus de selfies sans jamais les poster ?", comments: ["Le stockage iCloud de $pseudo coûte plus cher que son loyer"] },
    { category: "BOULOT", text: "Qui enverrait un mail à son boss bourré ?", comments: ["Objet : 'AUGMENTATION OU JE ME CASSE'. Envoyé à 2h37, Regretté à 8h00", "Et c'est une fin de carrière pour $pseudo"] },
    { category: "STYLE", text: "Qui a le plus mauvais goût en matière de tatouages ?", comments: ["T'inquiète $pseudo, c'est pas comme si c'était pour la vie..."] },
];